YAPP-Github/21st-iOS-Team-2-BE

src/main/java/com/yapp/ios2/fitfty/domain/hello/controller/HelloController.java
src/main/java/com/yapp/ios2/fitfty/domain/hello/dto/HelloDto.java
src/main/java/com/yapp/ios2/fitfty/domain/user/controller/UserController.java
src/main/java/com/yapp/ios2/fitfty/domain/user/dto/UserDto.java
src/main/java/com/yapp/ios2/fitfty/global/config/SecurityConfig.java
src/main/java/com/yapp/ios2/fitfty/global/error/ErrorResponse.java
src/main/java/com/yapp/ios2/fitfty/global/error/GlobalExceptionHandler.java
src/main/java/com/yapp/ios2/fitfty/s3/config/AmazonS3Config.java
src/main/resources/application.yaml

[Ios2 67/folder struct setting] 기본 구조 세팅용 패키지, 빈 파일들 추가 
[x] 본 구조 세팅 용 패키지, 빈 파일들 추가 
- 내용기재
- 내용기재

[Ios2 67/folder struct setting] 기본 구조 세팅용 패키지, 빈 파일들 추가 

---

src/test/java/com/yapp/ios2/fitfty/FitftyApplicationTests.java

[hotfix/IOS2-68/Dockerfile] 테스트코드 삭제

---

Dockerfile
src/test/java/com/yapp/ios2/fitfty/FitftyApplicationTests.java

[브랜치명] 작업 내용
ex) [Ios2 59/deploy] 배포 스크립트 추가
- 내용기재
- 내용기재

[develop] Deploy to EC2

---

build.gradle
lombok.config
src/main/java/com/yapp/ios2/fitfty/FitftyApplication.java
src/main/java/com/yapp/ios2/fitfty/domain/hello/controller/HelloController.java
src/main/java/com/yapp/ios2/fitfty/domain/hello/service/HelloService.java
src/main/resources/application-dev.yaml
src/main/resources/application-prod.yaml
src/main/resources/application.yaml
src/test/java/com/yapp/ios2/fitfty/FitftyApplicationTest.java
src/test/java/com/yapp/ios2/fitfty/domain/hello/service/HelloServiceTest.java

[Ios2 86] yml setting + 테스트 설정

---

build.gradle
src/main/java/com/yapp/ios2/fitfty/domain/hello/controller/HelloController.java
src/main/java/com/yapp/ios2/fitfty/global/config/JpaConfig.java
src/main/java/com/yapp/ios2/fitfty/global/config/SecurityConfig.java
src/main/java/com/yapp/ios2/fitfty/global/config/SwaggerConfiguration.java
src/main/resources/application-dev.yaml

- [ v] Swagger 추가
- [ v] 기본 DB h2 로 변경
- [ v] Jpa Config file 추가, csrf disabled 설정 변경
- [ v] 문서 업데이트
- 내용기재
- 내용기재

[IOS 85] Swagger Setting

---

src/main/java/com/yapp/ios2/fitfty/global/error/ErrorResponse.java
src/main/java/com/yapp/ios2/fitfty/global/error/GlobalExceptionHandler.java
src/main/java/com/yapp/ios2/fitfty/global/exception/BaseException.java
src/main/java/com/yapp/ios2/fitfty/global/exception/EntityNotFoundException.java
src/main/java/com/yapp/ios2/fitfty/global/exception/IllegalStatusException.java
src/main/java/com/yapp/ios2/fitfty/global/exception/InvalidParamException.java
src/main/java/com/yapp/ios2/fitfty/global/response/ErrorCode.java

CommonHttpRequestInterceptor 는 강의 따라서 코드 작성했을 때 HandlerInterceptorAdapter 에서 오류가 났어서 추후에 필요하면 추가하겠습니다!

[Ios2 87] Global error handling & Exception 추가

---

.github/workflows/deploy.yml

deploy.yml 파일 수정
application.yaml 파일 변수명 변경

[hotfix/IOS2 96-Struct-setting] Deploy 파일 수정

---

src/test/java/com/yapp/ios2/fitfty/domain/hello/service/HelloServiceTest.java

[hotfix/IOS2 96-Struct-setting] hello testcode 추석처리

---

.github/workflows/deploy.yml
src/test/java/com/yapp/ios2/fitfty/domain/hello/service/HelloServiceTest.java

[hotfix/develop] hello testcode 추석처리

---

src/main/resources/application-dev.yaml
src/main/resources/application-prod.yaml
src/main/resources/application.yaml

[HOTFIX] DB Settings

---

src/main/resources/application-prod.yaml

[Hotfix] 배포파일 포트번호 변경

---

src/main/java/com/yapp/ios2/fitfty/domain/board/Board.java
src/main/java/com/yapp/ios2/fitfty/domain/board/BoardInfo.java
src/main/java/com/yapp/ios2/fitfty/domain/board/BoardServiceImpl.java
src/main/java/com/yapp/ios2/fitfty/interfaces/board/BoardController.java
src/main/java/com/yapp/ios2/fitfty/interfaces/board/BoardDto.java

- 메인페이지 구현 시에 코디 추천하면서 조회수 +1 하는 기능도 추가하겠습니다.

[Ios2-139] 조회수 기능 추가

---

src/main/java/com/yapp/ios2/fitfty/domain/user/User.java
src/main/java/com/yapp/ios2/fitfty/domain/user/UserInfo.java
src/main/java/com/yapp/ios2/fitfty/domain/user/UserMapper.java
src/main/java/com/yapp/ios2/fitfty/domain/user/UserServiceImpl.java
src/main/java/com/yapp/ios2/fitfty/domain/user/auth/AuthService.java
src/main/java/com/yapp/ios2/fitfty/domain/user/auth/AuthServiceImpl.java
src/main/java/com/yapp/ios2/fitfty/interfaces/user/AuthController.java
src/main/resources/application.yaml

- 내 프로필 조회 API, 타유저 프로필 조회 -> filepath 포함하기
- 현재 사용자 권한 확인하는 api 추가하기
- Sign-in 단계에서 회원가입인지 / 기존 회원인지 여부 알려주기
- token expire 1년으로 변경
- 내용기재

[IOS-164] API 변경점 적용

---

src/main/java/com/yapp/ios2/fitfty/domain/board/BoardReader.java
src/main/java/com/yapp/ios2/fitfty/domain/board/BoardServiceImpl.java
src/main/java/com/yapp/ios2/fitfty/domain/user/UserService.java
src/main/java/com/yapp/ios2/fitfty/domain/user/UserServiceImpl.java
src/main/java/com/yapp/ios2/fitfty/infrastructure/board/BoardReaderImpl.java

[Ios2-163] 메인페이지 비회원 로직 수정

---

src/main/java/com/yapp/ios2/fitfty/domain/board/BoardInfo.java
src/main/java/com/yapp/ios2/fitfty/domain/board/BoardInfoMapper.java
src/main/java/com/yapp/ios2/fitfty/interfaces/board/BoardDto.java

[IOS2-165] 게시글 조회 시 작성일 반환

---

src/main/java/com/yapp/ios2/fitfty/domain/board/BoardInfo.java
src/main/java/com/yapp/ios2/fitfty/interfaces/board/BoardDto.java

[IOS-166] 사진촬영일 반환

---

src/main/java/com/yapp/ios2/fitfty/domain/report/ReportBoard.java
src/main/java/com/yapp/ios2/fitfty/domain/report/ReportCommand.java
src/main/java/com/yapp/ios2/fitfty/domain/report/ReportInfo.java
src/main/java/com/yapp/ios2/fitfty/domain/report/ReportMapper.java
src/main/java/com/yapp/ios2/fitfty/domain/report/ReportService.java
src/main/java/com/yapp/ios2/fitfty/domain/report/ReportServiceImpl.java
src/main/java/com/yapp/ios2/fitfty/domain/report/ReportUser.java
src/main/java/com/yapp/ios2/fitfty/domain/user/User.java
src/main/java/com/yapp/ios2/fitfty/domain/user/UserCommand.java
src/main/java/com/yapp/ios2/fitfty/domain/user/UserInfo.java
src/main/java/com/yapp/ios2/fitfty/domain/user/UserMapper.java
src/main/java/com/yapp/ios2/fitfty/domain/user/UserServiceImpl.java
src/main/java/com/yapp/ios2/fitfty/interfaces/report/ReportDto.java
src/main/java/com/yapp/ios2/fitfty/interfaces/user/UserDto.java

[Bug Fix] User Profile 오류 해결, User Phone 번호 삭제, Report 다중 선택 가능하도록 변경

---

src/main/java/com/yapp/ios2/fitfty/infrastructure/board/BoardReaderImpl.java

[IOS2-168] 게시글차단 비회원로직 수정 hotfix

---

src/main/java/com/yapp/ios2/fitfty/domain/user/User.java
src/main/java/com/yapp/ios2/fitfty/domain/user/UserCommand.java
src/main/java/com/yapp/ios2/fitfty/domain/user/UserServiceImpl.java
src/main/java/com/yapp/ios2/fitfty/domain/user/auth/AuthServiceImpl.java
src/main/java/com/yapp/ios2/fitfty/interfaces/user/UserController.java
src/main/java/com/yapp/ios2/fitfty/interfaces/user/UserDto.java

[Ios2 172] update logic change

---

src/main/java/com/yapp/ios2/fitfty/domain/board/BoardServiceImpl.java

[Ios2 172] 게시글 삭제 시 회원 북마크 삭제로직 추가

---

src/main/java/com/yapp/ios2/fitfty/domain/board/BoardServiceImpl.java
src/main/java/com/yapp/ios2/fitfty/domain/user/UserService.java
src/main/java/com/yapp/ios2/fitfty/domain/user/UserServiceImpl.java
src/main/java/com/yapp/ios2/fitfty/domain/user/UserStore.java
src/main/java/com/yapp/ios2/fitfty/infrastructure/user/BookmarkRepository.java
src/main/java/com/yapp/ios2/fitfty/infrastructure/user/UserStoreImpl.java

[hotfix] : 게시글 삭제 시 북마크 삭제 로직 변경. 

---

src/main/java/com/yapp/ios2/fitfty/domain/board/BoardServiceImpl.java
src/main/java/com/yapp/ios2/fitfty/domain/user/UserService.java
src/main/java/com/yapp/ios2/fitfty/domain/user/UserServiceImpl.java
src/main/java/com/yapp/ios2/fitfty/domain/user/UserStore.java
src/main/java/com/yapp/ios2/fitfty/infrastructure/user/BookmarkRepository.java
src/main/java/com/yapp/ios2/fitfty/infrastructure/user/UserStoreImpl.java

[hotfix] develop hot fix main에 반영

---

src/main/java/com/yapp/ios2/fitfty/global/config/SecurityConfig.java
src/main/java/com/yapp/ios2/fitfty/global/response/CommonControllerAdvice.java
src/main/java/com/yapp/ios2/fitfty/global/response/ErrorCode.java

- [v]request Matcher 관련 쓸모없는 url mapping 제거
- [v] not found handler 추가
- [v] 버그 수정
- 내용기재

[hotfix] prod 환경에서 h2-console 관련 로직 해결
